Repository Nault/Nault, pull requests merged in 2020-08, with the labels that each got.

#114 Representative UX improvements
  src/app/components/change-rep-widget/change-rep-widget.component.html
  src/app/components/change-rep-widget/change-rep-widget.component.ts
  src/app/services/representative.service.ts
  src/less/components/nav.less
Labels: enhancement

#117 Readme split
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: documentation

#123 Fix unknown reps not reporting 0% weekly uptime
  src/app/components/change-rep-widget/change-rep-widget.component.html
  src/app/services/ninja.service.ts
  src/app/services/representative.service.ts
  src/less/components/nav.less
Labels: bug

#126 Ledger guide and discord support
  README.md
  src/app/components/configure-wallet/configure-wallet.component.html
Labels: documentation

#116 Upgrade to Angular 10
  .browserslistrc
  e2e/tsconfig.e2e.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/pipes/currency-symbol.pipe.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.base.json
  tsconfig.json
  tslint.json
Labels: dependencies

#128 Badges
  README.md
Labels: documentation

#125 Code refactor and linting
  .github/workflows/linting.yml
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.ts
  src/app/components/address-book/address-book.component.ts
  src/app/components/change-rep-widget/change-rep-widget.component.ts
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/app/components/helpers/nano-account-id/nano-account-id.component.ts
  src/app/components/import-address-book/import-address-book.component.ts
  src/app/components/import-wallet/import-wallet.component.ts
  src/app/components/manage-representatives/manage-representatives.component.ts
  src/app/components/manage-wallet/manage-wallet.component.ts
  src/app/components/notifications/notifications.component.ts
  src/app/components/qr-modal/qr-modal.component.ts
  src/app/components/qr-scan/qr-scan.component.ts
  src/app/components/receive/receive.component.html
  src/app/components/receive/receive.component.ts
  src/app/components/remote-signing/remote-signing.component.ts
  src/app/components/representatives/representatives.component.html
  src/app/components/representatives/representatives.component.ts
  src/app/components/send/send.component.ts
  src/app/components/sign/sign.component.html
  src/app/components/sign/sign.component.ts
  src/app/components/sweeper/sweeper.component.ts
  src/app/components/transaction-details/transaction-details.component.ts
  src/app/components/wallet-widget/wallet-widget.component.ts
  src/app/pipes/account.pipe.ts
  src/app/pipes/amount-split.pipe.ts
  src/app/pipes/currency-symbol.pipe.ts
  src/app/pipes/fiat.pipe.ts
  src/app/pipes/rai.pipe.ts
  src/app/services/api.service.ts
  src/app/services/app-settings.service.ts
  src/app/services/desktop.service.ts
  src/app/services/ledger.service.ts
  src/app/services/modal.service.ts
  src/app/services/nano-block.service.ts
  src/app/services/ninja.service.ts
  src/app/services/node.service.ts
  src/app/services/notification.service.ts
  src/app/services/pow.service.ts
  src/app/services/price.service.ts
  src/app/services/qr-modal.service.ts
  src/app/services/remote-sign.service.ts
  src/app/services/representative.service.ts
  src/app/services/util.service.ts
  src/app/services/wallet.service.ts
  src/app/services/websocket.service.ts
  src/app/services/work-pool.service.ts
  src/app/welcome/welcome.component.ts
  src/polyfills.ts
  tslint.json
Labels: enhancement

#147 Improved balance layout on the accounts page
  src/app/components/accounts/accounts.component.css
  src/app/components/accounts/accounts.component.html
Labels: enhancement

#163 fix(sidebar): No more flickering when refreshing incoming
  src/app/services/wallet.service.ts
Labels: bug

#158 feat(qr-reader): Ability to scan an exported wallet/address book
  src/app/components/import-address-book/import-address-book.component.html
  src/app/components/import-address-book/import-address-book.component.ts
  src/app/components/import-wallet/import-wallet.component.html
  src/app/components/import-wallet/import-wallet.component.ts
  src/app/components/qr-scan/qr-scan.component.ts
Labels: enhancement

#165 fix(pow): New default base threshold of fffffff800000000
  src/app/components/sign/sign.component.ts
  src/app/services/pow.service.ts
Labels: enhancement

#167 fix(pow): Invalidate work cache with low threshold
  src/app/services/pow.service.ts
  src/app/services/util.service.ts
  src/app/services/work-pool.service.ts
Labels: enhancement

#189 refactor(desktop-app): Dynamic window size based on screen size
  desktop-app/src/desktop-app.ts
Labels: enhancement

#186 feat(wallets): Improved creation and import of wallets
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/configure-wallet/configure-wallet.component.css
  src/app/components/configure-wallet/configure-wallet.component.html
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/app/components/import-wallet/import-wallet.component.ts
  src/app/components/manage-wallet/manage-wallet.component.html
  src/app/services/wallet.service.ts
  src/less/nault-theme.less
Labels: enhancement

#195 feat(wallet-import): Added support for bip39 mnemonic
  src/app/components/configure-wallet/configure-wallet.component.html
  src/app/components/configure-wallet/configure-wallet.component.ts
Labels: enhancement

#200 feat(wallet-export): All active account indexes instead of last index
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/app/components/import-wallet/import-wallet.component.ts
  src/app/components/manage-wallet/manage-wallet.component.html
  src/app/components/manage-wallet/manage-wallet.component.ts
  src/app/services/wallet.service.ts
Labels: enhancement
