Repository Nault/Nault, pull requests merged in 2021-03, with the labels that each got.

#338 Remove The Nano Center representative
  src/app/services/nano-block.service.ts
Labels: maintenance

#352 Display amount of confirmed and total blocks under advanced options
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
Labels: enhancement

#353 Block height and other improvements for Transaction Details page
  src/app/components/transaction-details/transaction-details.component.css
  src/app/components/transaction-details/transaction-details.component.html
  src/app/components/transaction-details/transaction-details.component.ts
Labels: enhancement

#355 Add support for identicons
  src/app/app.module.ts
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/accounts/accounts.component.css
  src/app/components/accounts/accounts.component.html
  src/app/components/configure-app/configure-app.component.html
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/helpers/nano-identicon/nano-identicon.component.css
  src/app/components/helpers/nano-identicon/nano-identicon.component.html
  src/app/components/helpers/nano-identicon/nano-identicon.component.spec.ts
  src/app/components/helpers/nano-identicon/nano-identicon.component.ts
  src/app/components/receive/receive.component.html
  src/app/services/app-settings.service.ts
  src/assets/img/natricon-placeholder.svg
  src/assets/lib/nanoidenticons.min.js
  src/less/components/dark-mode.less
  src/less/nault-theme.less
Labels: enhancement

#356 Add min-width to the account column on Accounts page
  src/app/components/accounts/accounts.component.html
  src/less/nault-theme.less
Labels: bug
