Repository Nault/Nault, pull requests merged in 2021-06, with the labels that each got.

#390 Implemented watch-only accounts
  src/app/app.component.ts
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.html
  src/app/components/address-book/address-book.component.css
  src/app/components/address-book/address-book.component.html
  src/app/components/address-book/address-book.component.ts
  src/app/components/import-address-book/import-address-book.component.ts
  src/app/components/manage-representatives/manage-representatives.component.html
  src/app/components/receive/receive.component.html
  src/app/services/address-book.service.ts
  src/app/services/wallet.service.ts
  src/app/services/websocket.service.ts
Labels: enhancement

#394 Show address book results in remote signing
  src/app/components/remote-signing/remote-signing.component.html
  src/app/components/remote-signing/remote-signing.component.ts
Labels: enhancement

#397 Support UTF-16 characters in address book export
  src/app/components/account-details/account-details.component.html
  src/app/components/address-book/address-book.component.html
  src/app/components/address-book/address-book.component.ts
  src/app/components/import-address-book/import-address-book.component.html
  src/app/components/import-address-book/import-address-book.component.ts
Labels: enhancement

#399 Allow importing UTF-16 from address book file
  src/app/components/address-book/address-book.component.ts
Labels: bug

#401 Fixed: natricon size too big on mobile devices
  src/app/components/helpers/nano-identicon/nano-identicon.component.css
Labels: bug

#404 PWA instructions in the README
  README.md
Labels: documentation

#405 Fixing bugs in address book
  src/app/components/address-book/address-book.component.html
Labels: bug

#406 Auto-remove pending while receiving
  src/app/components/receive/receive.component.html
  src/app/components/receive/receive.component.ts
  src/app/services/wallet.service.ts
Labels: bug
