Repository Nault/Nault, pull requests merged in 2021-02, with the labels that each got.

#281 Account summary redesign
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/helpers/nano-account-id/nano-account-id.component.html
  src/app/components/sweeper/sweeper.component.html
  src/app/pipes/squeeze.pipe.ts
  src/less/nault-theme.less
Labels: enhancement

#286 Additional backend server - PowerNode
  src/app/services/app-settings.service.ts
Labels: enhancement

#283 Added desktop file for Linux
  desktop-app/assets/linux/128x128.png
  desktop-app/assets/linux/16x16.png
  desktop-app/assets/linux/24x24.png
  desktop-app/assets/linux/256x256.png
  desktop-app/assets/linux/32x32.png
  desktop-app/assets/linux/48x48.png
  desktop-app/assets/linux/512x512.png
  desktop-app/assets/linux/64x64.png
  package.json
Labels: enhancement

#294 Allow custom work server
  .github/release-drafter.yml
  README.md
  src/app/components/configure-app/configure-app.component.html
  src/app/components/configure-app/configure-app.component.ts
  src/app/services/api.service.ts
  src/app/services/app-settings.service.ts
  src/app/services/pow.service.ts
  src/less/nault-theme.less
Labels: enhancement

#295 Additional API Backend - Rainstorm City
  src/app/services/app-settings.service.ts
Labels: enhancement

#298 Custom new-wallet popup for Ledger
  src/app/components/configure-wallet/configure-wallet.component.ts
Labels: enhancement

#299 Replaced HID token
  src/index.html
Labels: maintenance

#300 Link to work server docs instead
  .github/release-drafter.yml
  README.md
  src/app/components/configure-app/configure-app.component.html
Labels: enhancement

#302 Include AUR mention
  README.md
Labels: documentation

#303 Configure wallet page redesign
  src/app/components/configure-wallet/configure-wallet.component.css
  src/app/components/configure-wallet/configure-wallet.component.html
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/less/components/nav.less
  src/less/nault-theme.less
Labels: enhancement

#308 Alert on long PoW and allow cancellation
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/wallet-widget/wallet-widget.component.html
  src/app/components/wallet-widget/wallet-widget.component.ts
  src/app/services/pow.service.ts
  src/app/services/work-pool.service.ts
Labels: enhancement

#309 Add night mode
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.css
  src/app/components/accounts/accounts.component.html
  src/app/components/address-book/address-book.component.css
  src/app/components/address-book/address-book.component.html
  src/app/components/address-book/address-book.component.ts
  src/app/components/configure-app/configure-app.component.css
  src/app/components/configure-app/configure-app.component.html
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/configure-wallet/configure-wallet.component.css
  src/app/components/configure-wallet/configure-wallet.component.html
  src/app/components/import-address-book/import-address-book.component.html
  src/app/components/manage-representatives/manage-representatives.component.html
  src/app/components/manage-representatives/manage-representatives.component.ts
  src/app/components/manage-wallet/manage-wallet.component.html
  src/app/components/notifications/notifications.component.css
  src/app/components/notifications/notifications.component.html
  src/app/components/qr-scan/qr-scan.component.html
  src/app/components/representatives/representatives.component.css
  src/app/components/representatives/representatives.component.html
  src/app/components/representatives/representatives.component.ts
  src/app/components/send/send.component.css
  src/app/components/send/send.component.html
  src/app/components/wallet-widget/wallet-widget.component.css
  src/app/services/address-book.service.ts
  src/app/services/app-settings.service.ts
  src/app/services/representative.service.ts
  src/app/welcome/welcome.component.html
  src/app/welcome/welcome.component.ts
  src/assets/img/nault-logo-night-mode.svg
  src/assets/img/qr-code.svg
  src/index.html
  src/less/components/_import.less
  src/less/components/dark-mode.less
  src/less/components/nav.less
  src/less/nault-theme.less
Labels: enhancement

#315 Compact the fractional part of NANO amounts
  src/app/app.component.html
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/accounts/accounts.component.html
  src/app/components/receive/receive.component.html
  src/app/components/representatives/representatives.component.html
  src/app/components/send/send.component.html
  src/app/components/sign/sign.component.html
  src/app/components/sweeper/sweeper.component.html
  src/app/components/transaction-details/transaction-details.component.html
  src/app/pipes/amount-split.pipe.ts
Labels: enhancement

#324 Hotfix for Remote Sign button not being shown on external accounts
  src/app/components/account-details/account-details.component.html
  src/less/nault-theme.less
Labels: bug

#325 Hotfix for invisible logo and QR code icon on desktop version
  src/app/components/account-details/account-details.component.css
  src/app/welcome/welcome.component.html
Labels: bug

#327 Persistent desktop window size and position
  desktop-app/src/desktop-app.ts
  package-lock.json
  package.json
Labels: enhancement

#328 Add representative donation button, various style improvements
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.css
  src/app/components/accounts/accounts.component.html
  src/app/components/representatives/representatives.component.css
  src/app/components/representatives/representatives.component.html
  src/app/services/representative.service.ts
  src/less/components/dark-mode.less
  src/less/nault-theme.less
Labels: enhancement

#329 Disable update check when downloading desktop update
  desktop-app/src/desktop-app.ts
Labels: enhancement
