Repository Nault/Nault, pull requests merged in 2021-01, with the labels that each got.

#239 fix: Proper validation of seed, mnemonic and private key during import
  src/app/components/configure-wallet/configure-wallet.component.ts
Labels: bug

#248 Fixing stuck processing state
  src/app/components/receive/receive.component.ts
  src/app/services/wallet.service.ts
Labels: bug

#249 Solving multiple-pow issues
  src/app/services/work-pool.service.ts
Labels: bug

#252 Add alert for representatives that plan to cease operations
  src/app/components/change-rep-widget/change-rep-widget.component.html
  src/app/services/representative.service.ts
Labels: enhancement

#253 Add note for Ledger device owners when importing a mnemonic
  src/app/components/configure-wallet/configure-wallet.component.html
Labels: enhancement

#254 Improve visibility of indexes for own accounts
  src/app/components/account-details/account-details.component.html
  src/app/components/accounts/accounts.component.css
  src/app/components/accounts/accounts.component.html
Labels: enhancement

#255 Wallet unlock form improvements
  src/app/components/wallet-widget/wallet-widget.component.css
  src/app/components/wallet-widget/wallet-widget.component.html
  src/app/components/wallet-widget/wallet-widget.component.ts
Labels: enhancement

#266 Remove stacked notifications that occur often
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.ts
  src/app/components/address-book/address-book.component.ts
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/app/components/manage-representatives/manage-representatives.component.ts
  src/app/components/manage-wallet/manage-wallet.component.ts
  src/app/components/receive/receive.component.ts
  src/app/components/send/send.component.ts
  src/app/components/sign/sign.component.ts
  src/app/services/wallet.service.ts
Labels: enhancement

#262 New rep summary page
  src/app/components/account-details/account-details.component.html
  src/app/components/configure-app/configure-app.component.html
  src/app/components/manage-representatives/manage-representatives.component.html
  src/app/components/representatives/representatives.component.css
  src/app/components/representatives/representatives.component.html
  src/app/components/representatives/representatives.component.ts
  src/less/nault-theme.less
Labels: enhancement

#269 Fix inaccurate total balance and being able to exceed 20 accounts upon import
  src/app/components/configure-wallet/configure-wallet.component.ts
  src/app/services/wallet.service.ts
Labels: bug

#267 Improving the PoW threshold used for different block types
  src/app/components/receive/receive.component.ts
  src/app/components/send/send.component.ts
  src/app/components/sign/sign.component.ts
  src/app/components/sweeper/sweeper.component.ts
  src/app/services/api.service.ts
  src/app/services/nano-block.service.ts
  src/app/services/pow.service.ts
  src/app/services/wallet.service.ts
  src/app/services/work-pool.service.ts
  src/assets/lib/pow/nano-webgl-pow.js
Labels: enhancement

#272 Choose different backend on random setting
  src/app/services/api.service.ts
Labels: bug

#275 Display account indexes on the representatives page
  src/app/components/representatives/representatives.component.html
  src/app/components/representatives/representatives.component.ts
Labels: enhancement

#274 Cleanup workflows
  .github/nault.png
  .github/release-drafter.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/electron.yml
  .github/workflows/electron_hash.yml
  .github/workflows/sonarcloud.yml
Labels: maintenance

#276 Allow custom local pow difficulty
  .gitignore
  src/app/components/configure-app/configure-app.component.html
  src/app/components/configure-app/configure-app.component.ts
  src/app/components/sign/sign.component.ts
  src/app/services/api.service.ts
  src/app/services/app-settings.service.ts
  src/app/services/nano-block.service.ts
  src/app/services/pow.service.ts
  src/app/services/util.service.ts
Labels: enhancement

#278 Enhanced app updater with user-choice
  desktop-app/src/desktop-app.ts
  package-lock.json
  package.json
Labels: enhancement

#280 Truncate addresses in the middle on the "Accounts" page
  src/app/components/accounts/accounts.component.html
  src/app/components/helpers/nano-account-id/nano-account-id.component.html
Labels: enhancement
