Repository Nault/Nault, pull requests merged in 2021-07, with the labels that each got.

#416 Stop fetching active_difficulty from the network
  src/app/components/configure-app/configure-app.component.ts
  src/app/services/api.service.ts
  src/app/services/pow.service.ts
Labels: enhancement

#417 Mobile-friendly account view (new homepage)
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/accounts/accounts.component.html
  src/app/components/accounts/accounts.component.ts
  src/less/components/_import.less
  src/less/components/dark-mode.less
  src/less/components/nano-card.less
  src/less/components/nav.less
  src/less/nault-theme.less
Labels: enhancement

#418 Fix not being able to scroll to the very top/bottom on mobile devices
  src/app/app.component.html
  src/app/app.component.ts
  src/less/components/nav.less
  src/less/nault-theme.less
Labels: bug

#419 Use local fonts
  src/assets/fonts/montserrat-v15-latin-300.eot
  src/assets/fonts/montserrat-v15-latin-300.svg
  src/assets/fonts/montserrat-v15-latin-300.ttf
  src/assets/fonts/montserrat-v15-latin-300.woff
  src/assets/fonts/montserrat-v15-latin-300.woff2
  src/assets/fonts/montserrat-v15-latin-500.eot
  src/assets/fonts/montserrat-v15-latin-500.svg
  src/assets/fonts/montserrat-v15-latin-500.ttf
  src/assets/fonts/montserrat-v15-latin-500.woff
  src/assets/fonts/montserrat-v15-latin-500.woff2
  src/assets/fonts/montserrat-v15-latin-700.eot
  src/assets/fonts/montserrat-v15-latin-700.svg
  src/assets/fonts/montserrat-v15-latin-700.ttf
  src/assets/fonts/montserrat-v15-latin-700.woff
  src/assets/fonts/montserrat-v15-latin-700.woff2
  src/assets/fonts/montserrat-v15-latin-regular.eot
  src/assets/fonts/montserrat-v15-latin-regular.svg
  src/assets/fonts/montserrat-v15-latin-regular.ttf
  src/assets/fonts/montserrat-v15-latin-regular.woff
  src/assets/fonts/montserrat-v15-latin-regular.woff2
  src/assets/fonts/open-sans-v20-latin-300.eot
  src/assets/fonts/open-sans-v20-latin-300.svg
  src/assets/fonts/open-sans-v20-latin-300.ttf
  src/assets/fonts/open-sans-v20-latin-300.woff
  src/assets/fonts/open-sans-v20-latin-300.woff2
  src/assets/fonts/open-sans-v20-latin-regular.eot
  src/assets/fonts/open-sans-v20-latin-regular.svg
  src/assets/fonts/open-sans-v20-latin-regular.ttf
  src/assets/fonts/open-sans-v20-latin-regular.woff
  src/assets/fonts/open-sans-v20-latin-regular.woff2
  src/assets/fonts/roboto-mono-v13-latin-regular.eot
  src/assets/fonts/roboto-mono-v13-latin-regular.svg
  src/assets/fonts/roboto-mono-v13-latin-regular.ttf
  src/assets/fonts/roboto-mono-v13-latin-regular.woff
  src/assets/fonts/roboto-mono-v13-latin-regular.woff2
  src/index.html
  src/less/components/_import.less
  src/less/components/font.less
Labels: enhancement

#420 Use NodeJS 14
  .github/workflows/electron_hash.yml
  .github/workflows/ghpages.yml
  .github/workflows/linting.yml
  DEVELOPMENT.md
  Dockerfile
  package-lock.json
Labels: dependencies

#431 Implement new transactions list and menus for mobile devices
  src/app/app.module.ts
  src/app/components/account-details/account-details.component.css
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/helpers/nano-account-id/nano-account-id.component.html
  src/app/components/helpers/nano-account-id/nano-account-id.component.ts
  src/app/components/helpers/nano-transaction-mobile/nano-transaction-mobile.component.html
  src/app/components/helpers/nano-transaction-mobile/nano-transaction-mobile.component.less
  src/app/components/helpers/nano-transaction-mobile/nano-transaction-mobile.component.spec.ts
  src/app/components/helpers/nano-transaction-mobile/nano-transaction-mobile.component.ts
  src/app/components/notifications/notifications.component.css
  src/less/components/dark-mode.less
  src/less/nault-theme.less
Labels: enhancement

#455 Use the new style for confirming remote signing
  src/app/components/sign/sign.component.css
  src/app/components/sign/sign.component.html
  src/app/components/sign/sign.component.ts
Labels: enhancement

#454 Use new alert style for sweeper
  src/app/components/sweeper/sweeper.component.ts
Labels: enhancement

#452 Export account transaction history as csv files
  src/app/components/manage-wallet/manage-wallet.component.css
  src/app/components/manage-wallet/manage-wallet.component.html
  src/app/components/manage-wallet/manage-wallet.component.ts
  src/app/services/api.service.ts
Labels: enhancement

#459 Use mobile transactions layout on the "Receive" page on small viewports
  src/app/components/account-details/account-details.component.html
  src/app/components/account-details/account-details.component.ts
  src/app/components/receive/receive.component.html
  src/app/components/receive/receive.component.ts
Labels: enhancement

#458 Alert when switching wallet storage option to none
  src/app/components/configure-app/configure-app.component.ts
Labels: enhancement
